### ISSUE TITLE
Version 0.5 startet nicht mit MoneyMoney

### ISSUE THREAD

**Issue by tbrandt77** [UdoBretz/Bitcoin-MoneyMoney#3]
Hallo @UdoBretz, 

habe versucht Ihre Bitcoin.lua Version 0.5 in meiner MoneyMoney Installation zu integrieren. Jedoch bekomme ich eine Meldung, dass etwas mit der Signatur nicht stimmen würde. Ist das ein Bug oder muss ich noch etwas beachten?

Viele Grüße
@tbrandt77

**Comment by UdoBretz** [comment]
Hallo,

am besten laden Sie die extension über die Seite https://moneymoney-app.com/extensions/. Der Entwickler von MoneyMoney signiert die Extensions und stellt sie dort offiziell zur Verfügung. 

Viele Grüße,
Udo Bretz

**Comment by tbrandt77** [comment]
Vielen Dank, das wars. Extension läuft jetzt. Tolle Arbeit!

**Comment by UdoBretz** [comment]
Vielen Dank!
