### ISSUE TITLE
Kein Konto "Bitcoin"

### ISSUE THREAD

**Issue by GabZach** [UdoBretz/Bitcoin-MoneyMoney#4]
Ich habe die Extension installiert wie angegeben, aber es gibt in der Liste der Konten "Andere" keinen "Bitcoin" Account ...
(Aktuelle MM Version: 2.4.6)

**Comment by GabZach** [comment]
In MM / Einstellungen / Extensions  ist sie auch nicht zu sehen ...

**Comment by UdoBretz** [comment]
Bitte versuchen sie das Bitcoin-Plugin von hier herunterzuladen: https://moneymoney-app.com/extensions/
Dieses wurde vom Hersteller signiert, damit sollte es funktionieren.

**Comment by GabZach** [comment]
Danke für den Hinweis! ein Vorschlag: auf der Webseite von MM/extensions sollte ein entsprechender Hinweis stehen, dass nur die signierten Versionen von dieser Webseite funktionieren.
